/**
 * Define the required js libraries needed for this application. The compiler will merge them all into a single download
 */
require('angular');
require('ui-bootstrap');
require('ui-bootstrap-tpls');
require('datetimepicker');
require('angular-cookies');
require('angular-resource');
require('angular-route');
require('angular-sanitize');
require('angular-ui-router');
require('loading-bar');
require('statehelper');
require('bootstrap');
require('commangular');
require('es5-shim');
require('jquery');
require('jquery-ui');
require('json3');