object @week
attributes :id,
           :week_type_id,
           :name,
           :slug,
           :season_id,
           :starts_at,
           :ends_at,
           :reminder_sent_at,
           :complete,
           :display,
           :date_range,
           :type,
           :game_count,
           :game_complete_count,
           :game_tbd_count,
           :season_type
