object @league
attributes :id,
           :name,
           :public,
           :elimination,
           :eliminate_on_tie,
           :season_id,
           :start_week_id,
           :max_teams_per_user,
           :max_picks_per_week,
           :message,
           :started,
           :closed,
           :format,
           :team_count,
           :start_week_display,
           :season_name,
           :commish_names,
           :commish_ids